# Generated by Django 3.1.2 on 2020-10-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='q1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='q2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='q3',
            field=models.BooleanField(default=False),
        ),
    ]
