# Generated by Django 3.1.1 on 2020-10-13 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-pub_date']},
        ),
    ]
