# Generated by Django 3.1.1 on 2020-10-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='C_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.BooleanField(default=False)),
                ('q2', models.BooleanField(default=False)),
                ('q3', models.BooleanField(default=False)),
                ('q4', models.BooleanField(default=False)),
                ('q5', models.BooleanField(default=False)),
                ('q6', models.BooleanField(default=False)),
                ('q7', models.BooleanField(default=False)),
                ('q8', models.BooleanField(default=False)),
            ],
        ),
    ]
