# Generated by Django 2.1.1 on 2020-10-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='q5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='q6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='q7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='q8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='q9',
            field=models.BooleanField(default=False),
        ),
    ]
