# Generated by Django 2.1.1 on 2020-10-02 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201002_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='q9',
        ),
    ]
