# Generated by Django 3.1.1 on 2020-10-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='text',
            field=models.TextField(max_length=200),
        ),
    ]
